### PR TITLE
Fix entities being invisible

### PR DESCRIPTION
**Pull request by CyberCat319**

### CODE REVIEW

**Comment by douira** [comment]
Doesn't this defeat the point of entity culling?

**Comment by IMS212** [comment]
It does. The proposed change makes it so occlusion culling has no effect on entities.

**Comment by douira** [comment]
If you are experiencing problems with entity culling, please file a bug report or come to the discord server if you need support. Further, entity culling can be disabled with a setting in the video options.

**Comment by Felix14-v2** [comment]
> If you are experiencing problems with entity culling, please file a bug report

A kind reminder that one already exists ._. 
https://github.com/CaffeineMC/sodium-fabric/issues/2696

**Pull request closed without merging**
